spring:
    data:
        mongodb:
            uri: mongodb://localhost:27017/f1nity
            host: localhost
            port: 27017
            database: f1nity

auth:
  mongodb:
    uri: mongodb://localhost:27017/authentication
    host: localhost
    port: 27017
    database: authentication
    authentication-database: admin


news:
  api: 67812bd06ac34a7f90694607da85dcb5
  url: https://newsapi.org/v2/everything
  domains: motorsport.com
  language: en
  sortBy: publishedAt
  pageSize: 10
  query:
    exclude: speed, technology, business, health, science
    keywords: Formula 1,racing,Grand Prix
redis:
  url: redis://localhost:6379
  ttl: 86400