server:
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}

auth:
  mongodb:
    uri: ${AUTH_MONGO_URI}

news:
  api: ${NEWS_API_KEY}
  url: https://newsapi.org/v2/everything
  domains: motorsport.com
  language: en
  sortBy: publishedAt
  pageSize: 10
  query:
    exclude: speed, technology, business, health, science
    keywords: Formula 1,racing,Grand Prix
redis:
  url: ${REDIS_URL}
  password: ${REDIS_PASSWORD}
  ttl: 86400
